baseURL = "https://raine.guagua7/"
languageCode = "en-us"
title = "Raine Zhao"
theme = "PaperMod"

[params]
  homeMode = "profile"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowToc = false
  hideFooter = false

  [params.tokens]
    main = "#1f1f1f"
    link = "#444444"
    hover = "#1f1f1f"

  [params.profileMode]
    enabled = true
    title = "Raine Zhao"
    subtitle = "Quietly thinking & building."
    imageUrl = ""
    buttons = [
      { name = "About", url = "/about/" },
      { name = "Email", url = "mailto:raine.zhao7@outlook.com" }
    ]
