baseURL = "https://hugo-paper-mod-ncgp.vercel.app/"
languageCode = "en-us"
title = 七千里路云和月
theme = "PaperMod"

[params]
  homeMode = "profile"
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowToc = false
  hideFooter = false

  [params.tokens]
    main = "#1f1f1f"
    link = "#444444"

  [params.profileMode]
    enabled = true
    title = "Raine"
    subtitle = "Media & Communication Researcher"
    imageUrl = ""
    buttons = []
